# Generated by Django 4.0.2 on 2022-02-21 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_place_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
