# Generated by Django 4.0.2 on 2022-02-21 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_place_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='priority',
        ),
        migrations.AddField(
            model_name='place',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='place',
            name='isStarred',
            field=models.BooleanField(default=False),
        ),
    ]
