# Generated by Django 4.0.2 on 2022-02-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_rename_isstarred_place_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='dateAdded',
        ),
    ]
